### PR TITLE
fixes #92 and some pdf rendering improvements

### LINKED ISSUE #92: get annotations crashes with SIGSEGV
Generating annotations fails with the following message:

```
ReMarkable Cloud API Shell
downloading: [unitest]...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x85b1a9]

goroutine 1 [running]:
github.com/juruen/rmapi/annotations.(*PdfGenerator).Generate(0xc000471b40, 0x0, 0x0)
        /home/ddd/go/src/github.com/juruen/rmapi/annotations/pdf.go:62 +0x439
github.com/juruen/rmapi/shell.getACmd.func1(0xc0003f8410)
        /home/ddd/go/src/github.com/juruen/rmapi/shell/geta.go:54 +0x765
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc0001220f0, 0xc00009c070, 0x2, 0x2, 0x11, 0xc000756a50, 0xc000254e40)
        /home/ddd/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x2f5
github.com/abiosoft/ishell.handleInput(0xc0001220f0, 0xc00009c070, 0x2, 0x2, 0xc00004fba8, 0xc000113ef0)
        /home/ddd/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x4d
github.com/abiosoft/ishell.(*Shell).Process(...)
        /home/ddd/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:200
github.com/juruen/rmapi/shell.RunShell(0xc000458370, 0xc, 0xc0000f9f10)
        /home/ddd/go/src/github.com/juruen/rmapi/shell/shell.go:72 +0x909
main.run_shell(0xc000458370)
        /home/ddd/go/src/github.com/juruen/rmapi/main.go:14 +0x2f
main.main()
        /home/ddd/go/src/github.com/juruen/rmapi/main.go:38 +0x12c
```

go version go1.14.1 linux/amd64

File to reproduce:  https://github.com/ddvk/rmapi/blob/broken/test_data/unitest.zip

edit: Data is nil, and the check got removed

### PR DESCRIPTION
**Pull request by ddvk**
fix for #92 
fix: change the members of Transform struct to float32 (the the view is adjusted)
re-add the logic to add page numbers
options to generate all pages / and only the annoations without the background
wip: add highlighting

needs work: depending on the pdf size the alignment of the notes is wrong. i've a pdf generation test with several samples. the remarkable does not generate A4 pages, there is some crop/transform with the Transform struct, still haven't figured it out

### CODE REVIEW

**Comment by juruen** [comment]
Thanks for this! Let me know when this is ready to be reviewed and merged!

**Comment by ddvk** [comment]
This is ready for review
The notes fit the pdf.  
I've tried duplicate the rm behavior (generate notes with size 445x594, otherwise use the original document size.
The case where the pdf is "adjusted/cropped" has not been covered yet.

**Comment by juruen** [comment]
@ddvk thank you so much for fixing this! ❤️

**Comment by juruen** [comment]
@ddvk  Would you mind removing the `wip` from the PR tittle? Thanks!

**Pull request merged**
