### PR TITLE
Simpler version of v5 support

### PR DESCRIPTION
**Pull request by lobre**
Hello,

In regards to #67.

Here are my suggestions to keep the `rm` package as simple as possible while still supporting v3 and v5. I think having an interface implemented by a v3 reader and a v5 reader was a good idea in theory but was bringing some duplication of code. And as we don't know where Remarkable is going with these formats, it is hard to predict that we will easily be able to just implement this interface for future versions. They might totally "break the contract".

I also added the version of the file in the `rm` struct. It is important to have it as this `rm` package is supposed to do unmarshaling and marshaling (while still not implemented). So we need a way to recreate a `.rm` binary file from a `rm` struct by reapplying the correct version.

Another choice I have made here is to keep the distinction of brushes coming from v3 apart from those coming from v5. I agree that is what a good idea to merge brushes defined in v3 and v5 so a developer using the `rm` package could just check that a line has been done with simply the BallPoint  without caring if it is the v3 or v5. However, we need to keep track of brush IDs in case of marshaling. We could think of a smarter way of doing this now that we have the version in the `rm` struct. For example, using a slice of correspondence between v3 and v5 IDs that would allow to recreate the correct ID according to the current file version.

I have also added some factorisation on the test and gofmt all the files because they were not entirely formatted.

Feel free to comment if any remarks/comments,
Loric

### CODE REVIEW

**Comment by ddvk** [comment]
Hi, it's nice that work continues.

my idea was to abstract the domain logic and separate it from the concrete representation i.e you have brushes,layers, points and lines and some drawing logic. 

Of course in the future they could add more tools which would require a change in the domain.

We could have version specific marshaller which would have enabled version conversion.

IMHO spraying if-s to handle version specific cases to makes the code brittle and is a "violation" of [OCP](https://dave.cheney.net/2016/08/20/solid-go-design)

**Comment by lobre** [comment]
I am totally on the same page regarding these SOLID principles or more globally on the fact that the domain should be as much abstracted as possible from the logic.

On this project however I am just trying to be a little bit pragmatic. We are dealing with a dependency we don't have control over. There is no interface guaranteeing that Remarkable won't break things in the future. We don't even know if they will continue to use a binary format in tomorrow's version.

That's why I try to also be "pragmatic" in coding in some way. I feel that adding layers of design makes obviously the project more robust but also more complicated to understand for someone wanting to contribute (and more complicated to maintain in that kind of open-source context).

The difficulty is to bring just enough engineering to avoid being stuck in the future. But with this example, we were adding ~100 lines of duplicated code for just a new "unknown" field in the binary. This is where I think violating the rules and add a small "if" could make sense.

It is an interesting debate though. I'd be interested in trying to find the "middle ground" with a design that would allow more separation but without that many duplication ;-).

**Comment by rorycl** [comment]
> It is an interesting debate though. I'd be interested in trying to find the "middle ground" with a design that would allow more separation but without that many duplication ;-).

Hi @lobre. Could you have a look at [rm2pdf](https://github.com/rorycl/rm2pdf)? I thought a bit about abstractions but only wrote rm2pdf/rmparse for version 5 .rm files. All the stroke definitions are in mr2pdf/rmpdf/stroke and although the map deals with pen ids from both version 3 and 5 files (I think) there is probably a better way to do it. I hadn't thought about writing .rm files.

I'd be grateful for some comments on:
1. rm2pdf in general
2. to learn if there is a source of v3 .rm files, together with PDF output
(my reference for v5 is https://github.com/rorycl/rm2pdf/blob/master/testfiles/reMarkable_output.pdf and the associated files prefixed cc8313bb-5fab-4ab5-af39-46e6d4160df3

**Comment by lobre** [comment]
Hi @rorycl,

I've thrown a look rapidly and the outcomes is awesome! I have just quiclky had a look to the code but not much into details. I'll dig more when I have more time.

It is funny to see that many of us are trying to answer the same needs with this tablet in our little corner! It would definitely be cool to share and put together something bigger!

Having a set of pure golang libraries to interact with the Remarkable really gives superpowers to the tablet!

Loric

**Comment by rorycl** [comment]
Hi @lobre 

Thanks for your note, and great to hear it is working for you.

I agree it would be great to have a set of nice clean go libraries/modules to work with to support the reMarkable!

Some PDFs, such as those produced by Word, and (more surprisingly) pdflatex break the PDF page importer sometimes. It has always been possible to fix that problem using pdftk, for instance doing `pdftk <orig.pdf> cat output <fixed.pdf> && mv <orig.pdf> <problem.pdf.bkp> && mv <fixed.pdf> <orig.pdf>`; but it would be good not to have to do that.

If I have time this weekend I'll look at the specific issue reported by github.com/jung-kurt/gofpdf/contrib/gofpdi -- which looks at first like a PDF xref problem.

Working with straightforward notes aren't affected by this problem.

Cheers
Rory

**Pull request merged**
