### PR TITLE
Rename api.v2 to cloud

### PR DESCRIPTION
**Pull request by lobre**
Hi @juruen ,

I was thinking again about the folder architecture of the project. We have recently added support of Go modules. This means we can now empower even more the semantic versionning of `rmapi` as a module.

That's why I think that `cloud` might be a better name than `api.v2` for this new package. It represents better what the package is doing: interacting with the reMarkable Cloud. And "versioning" of packages would have better sense to be handled globally using the versioning of the module.

Speaking about the version of the module, we still did not reach the v1.0.0 which can be defined in semver as: "If you have a stable API on which users have come to depend".

That's why I was wondering if we could benefit of not having reached v1 to try to fit with the good practice of Golang saying that commands (containing package main) should reside in a `cmd` folder at the root of the repository.

See: https://github.com/golang-standards/project-layout/tree/master/cmd

That can help to differenciate packages acting as libraries (here located at the root) from real command programs.

So I was thinking to shift the `shell` package under `cmd/shell` when refactoring the `shell` package to use the new `cloud` and `archive` package libraries.

The drawback of this shift is that people depending in their project on `shell` would have build brakes forcing them to switch to the `cloud`/`archive` packages (which I think could be a good thing because these packages are meant to be used externally while `shell` contains really specific behaviors of the `rmapi` application).

What do you think about these ideas?
Thanks a lot,
Loric

### CODE REVIEW

**Comment by lobre** [comment]
Hi @juruen , what about this PR?

**Comment by lobre** [comment]
I have just created v0.0.7 to include these changes.
I see the release is automatically built with GitHub actions. That's neat!

**Comment by juruen** [comment]
@lobre Did you follow https://github.com/juruen/rmapi/blob/master/docs/create-release.md ?

If you didn't, let me know and I'll fix it.

**Comment by lobre** [comment]
Oh no sorry, I thought just creating and pushing the tag was enough :/

**Pull request merged**
