### PR TITLE
update 1.5 sync urls #259

### PR DESCRIPTION
**Pull request by ddvk**

### CODE REVIEW

**Comment by arjenpdevries** [comment]
Trying out the pull request, I get a different error:
```
ERROR: 2022/10/07 18:36:35 main.go:19: Error:  Failed to upload file [/home/arjen/Downloads/tree-movers-distance-2210.01906.pdf] PutBlobStream: got status code 400
```

**Comment by ddvk** [comment]
ok, then the urls were correct , just the request was wrong

**Comment by ddvk** [comment]
can you try again?

**Comment by arjenpdevries** [comment]
Back to `ERROR: 2022/10/08 15:51:39 apictx.go:431: cannot send sync request failed with status 500`.

**Comment by ddvk** [comment]
I'm giving up for now, it could be it got migrated on their end, so we have to use the new urls.

**Comment by arjenpdevries** [comment]
The interesting thing is that the file does get uploaded correctly, as far as I can assess. So the 500 may just be something in the protocol that we do not know/understand.

**Comment by arjenpdevries** [comment]
In `SyncComplete` of `blobstorage.go`, the `http.Post` call has `nil` as final argument, where in other occurrences of `http.Post` the code uses the address of a variable `res` of type `model.BlobStorageResponse`.

Could that be the problem?

**Comment by ddvk** [comment]
so I've reverted to using the agein new urls and trying to find out why the error occurs. did some more changes, 

you can try again. also enable tracing:
`export RMAPI_TRACE=1`  before running rmapi

**Comment by arjenpdevries** [comment]
```
ERROR: 2022/10/08 19:28:30 main.go:19: Error:  Failed to upload file [/home/arjen/Downloads/tree-movers-distance-2210.01906.pdf] PutBlobStream: got status code 400
```

The trace ends in:
```
Trace: 2022/10/08 19:30:06 transport.go:312: PutBlobSteam: Response: HTTP/2.0 400 Bad Request
Content-Length: 282
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: application/xml; charset=UTF-8
Date: Sat, 08 Oct 2022 17:30:06 GMT
Server: UploadServer
X-Guploader-Uploadid: ADPycdv1lT8hjS6TVwYdwrP8-GqtCo72eQYrJ0_lchTF0-r5QOOu1Ai5XwSvRN-ABlwLiOVbkekKfWLFaz3m6kb69POIYDfVrZN3

<?xml version='1.0' encoding='UTF-8'?><Error><Code>MalformedSecurityHeader</Code><Message>Your request has a malformed header.</Message><ParameterName>x-goog-content-length-range</ParameterName><Details>Header was included in signedheaders, but not in the request.</Details></Error> <nil>
```

**Comment by ddvk** [comment]
in the trace can you post the response of the /upload request before that, should be a json, the one that has "url":"some google address"

**Comment by arjenpdevries** [comment]
You can take a look [here](http://www.cs.ru.nl/~arjen/tmp/rmapi.trace.txt) - will remove it in 30 minutes or so (sorry, a bit paranoid maybe, but looks like it could do harm if ppl want to abuse the info in the trace?)

**Comment by ddvk** [comment]
thanks a lot, please remove it, asap.  there are some tokens in the dump (that expire after 24h)

**Comment by arjenpdevries** [comment]
(Just for the record: removed link to file, and access rights.)

**Comment by ddvk** [comment]
ok, added the findings

**Comment by arjenpdevries** [comment]
Still a problem... do you need a new trace file?

**Comment by ddvk** [comment]
i'll get back to you, when I have time

**Comment by arjenpdevries** [comment]
Tnx @ddvk

**Pull request merged**
